import { createApi, fetchBaseQuery } from '@reduxjs/toolkit/query/react';
import { accessToken } from '../../utils/getAccessToken';
import { spotify_base_url } from '../../config';
import { params } from './params';

export const newReleasesApi = createApi({
    reducerPath: 'newReleasesApi',

    // The base URL for the API.
    baseQuery: fetchBaseQuery({
        baseUrl: `${spotify_base_url}/browse/new-releases?${params}`,
        prepareHeaders: (headers, { getState }) => {
            headers.set(
                'Authorization',
                `Bearer ${accessToken}`,
            )
            return headers
        }
    }),
    endpoints: (builder) => ({
        getNewReleases: builder.query<any[], void>({
            query: () => '',
        })
    })
});

// this useGetNewReleases hook is automatically generated by the createApi function.
export const { useGetNewReleasesQuery } = newReleasesApi;
